sudo: false

matrix:
  include:
    - os: osx
      language: generic

install:
  - brew --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - pip3 install pipenv
  - pipenv sync

script:
  - pipenv run ansible --version
  - pipenv run test:lint
  - pipenv run test:unit
