sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode10.2 # macOS 10.14
      language: generic
    - os: osx
      osx_image: xcode9.4 # macOS 10.13
      language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall --ignore-dependencies python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - pip3 install pipenv
  - pipenv sync --dev

script:
  - pipenv run ansible --version
  - pipenv run test:lint
  - pipenv run test:unit:module
  - pipenv run test:unit:role
