sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode10.2 # macOS 10.14
      language: generic
    - os: osx
      osx_image: xcode9.4 # macOS 10.13
      language: generic

env:
  global:
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"
    - PIPENV_VENV_IN_PROJECT=1

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade pyenv; fi
  - eval "$(pyenv init -)"
  - pyenv install 3.7.4
  - pyenv global 3.7.4
  - pip install --upgrade pip
  - pip --version
  - pip install pipenv
  - pipenv --version
  - pipenv sync --dev --python 3.7.4

script:
  - pipenv run ansible --version
  - pipenv run test:lint
  - pipenv run test:unit:module
  - pipenv run test:unit:role
