---
- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: present
    update_homebrew: yes
  when: not vscode.skip_install | default(False)
  become: no

- name: Install extensions for Visual Studio Code
  vscode:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ vscode.extensions }}"
  become: no
